### ISSUE TITLE
Bug: Failure to load due to bad import

### ISSUE THREAD

**Issue by cannotilever** [Furglitch/modorganizer2-nxm-collection-dl#4]
The plugin fails to load with the error:
```
ImportError: Cannot import name `QApplication from 'PyQt6.QtCore'
```
`QApplication` should be imported from `PyQt6.QtWidgets` instead. 

Bug was introduced in 62b069c. 

Screenshot:

<img width="501" height="452" alt="Image" src="https://github.com/user-attachments/assets/c0ad2715-0e2e-4777-8084-0fb62c2bd0c0" />
